<div id = "grid">
<div class="ui grid">
<div class="ui grid">
  <div class="one wide column"></div>


    	<div class="twelve wide column">
    <div class="ui segment">
      
        <!--<div class="ui top attached tabular menu">
                                        <a class="active item"> !-->
<div class = "ui top attached label red"><b>ABOUT</b></div><br>
   <!--       <a class= "item"><strong>FAQ's</strong></a></div></div><br> !-->

        <strong>Online Judge developed as a part of <a href="http://www.pclub.in/">Programming Club</a>
         IITK Summer project 2014.</strong><br>
        Online judge is an automated judge system to run programming contests.
        <br><br> <!-- It has a mechanism to submit problem solutions, have them judged fully automatically and provides (web)interfaces for teams, the jury and the general public.

online judge is meant to be used in programming contests like the WPC programming contests, where teams are on-site and there is a fixed problem set and timeframe.
<br>
Key aspects include:

Webinterface for portability and simplicity<br>
<ui>
<strong>Scalable:</strong> distributed judging is easy</li>
<li>Modular system for plugging in languages/compilers</li>
<li>Features rejudging, clarifications, detailed submission/judging info</li>
<li>Lightweight, depends on standard software to do its task</li>
<li>Designed with security in mind</li>
<li>It's Open Source, Free Software</li><br> -->
<!-- Mail me at <a href="mailto:admin@gmail.com">admin@gmail.com</a><br><br>
 -->  <!--<a name="faq"></a>
  <a href="#onj1">How does ONJ test whether my solution is correct or not?</a><br>
  <a href="#onj2">How should I test my program?</a><br>
  <a href="#onj3">What am I allowed to post as a comment for a problem?</a><br>
  <a href="#onj4">How does the time limit work?</a><br>
  <div class="ten wide column">
    <div class="ui segment">
  <a name="onj1"></a><strong>How does onj test whether my solution is correct or not?</strong><br>
Your code is tested by a computer automatically, not by a human being, and you have to write your code accordingly.
For each problem, Codechef will have one or more input files, each according to the specifications mentioned in the problem statement, and corresponding correct output files. Codechef will run your program on each of the input files by redirecting the standard input stream to an input file, and the standard output stream to another file. The output generated by your program must match the correct output *exactly* in order to be judged correct.
Some consequences of this:
If your program starts by printing 'Enter the number' and the problem does not tell you to do so, then since this is not part of the correct output, you will be never be judged correct regardless of what the rest of your program does.
As all that matters is that the output files match, it makes no difference at all at what point in your program's execution that this output is written. So there is no need to read all of the input before starting output; it is much more common to just print out each result as you are reading through the input.
If you use any method other than using the standard input and output streams - for example, using command line arguments, reading from a file, opening up some sort of dialog box, or otherwise - you will never be judged correct.
      <br></div></div>
      <div class="ten wide column">
    <div class="ui segment">
 <a name="onj2"></a><strong>How should I test my program?</strong><br>
The best way of testing your program is doing so in exactly the same way that Codechef does. Create an input file (for example, in.txt). Then run your program from the command line, using < and > to redirect the streams. For example:
java test < in.txt > out.txt<br>
or<br>
test.exe < in.txt > out.txt<br>
Your output will then be in the out.txt file, so you can check if it is correct.
Often people forget to print a new line between test cases, but this is easily avoided if you use this method of testing.
<br></div></div><div class="ten wide column">
    <div class="ui segment">
<a name="onj3"></a><strong>What am I allowed to post as a comment for a problem?</strong><br>

If the problem is part of a contest that is still in progress:
 <ui>
<li>Do NOT post code.</li>
<li>Do NOT post a comment asking why your solution is wrong.</li>
<li>Do NOT post a comment asking if you can be given the test case your program fails on.</li>
<li>Do NOT post a comment asking how your solution can be improved.</li>
<li>Do NOT post a comment giving any hints or discussing approaches to the problem, or what type or speed of algorithm is required.</li>
</div>
</div><br>
<div class="ten wide column">
    <div class="ui segment">
<a name="onj4"></a><strong>How does the time limit work?</strong><br>
Your program must read, process, and output the result for an input file within the specified time limit. The input file will be of the format mentioned in the problem.<br>
<br>This means, if the input contains multiple test cases, your code must complete ALL of these within that time limit. If the time limit is 2 seconds, and there may be 1000 test cases, your program shouldn't be taking 1 second per test case - it needs to run all 1000 in under 2 seconds.
<br>Some programming languages are slower than others, and are thus given more time. Currently, Java and Python are allowed twice the time limit, while Ruby, PHP and Lisp are allowed to run for up to three times the time limit.

</div>
</div> 

<div class="ui cube shape">
  <div class="sides">
    <div class="active side">
      <div class="content">
        <div class="center">
          1
        </div>
      </div>
    </div>
    <div class="side">
      <div class="content">
        <div class="center">
          2
        </div>
      </div>
    </div>
    <div class="side">
      <div class="content">
        <div class="center">
          3
        </div>
      </div>
    </div>
    <div class="side">
      <div class="content">
        <div class="center">
          4
        </div>
      </div>
    </div>
    <div class="side">
      <div class="content">
        <div class="center">
          5
        </div>
      </div>
    </div>
    <div class="side">
      <div class="content">
        <div class="center">
          6
        </div>
      </div>
    </div>


      </div>
  </div>
  <div class="ui ignored divider"></div>
      <div class="ui ignored icon direction buttons">
        <div class="ui button" data-animation="flip" title="Flip Left" data-direction="left" onclick="function()"><i class="left long arrow icon"></i></div>
        <div class="ui button" data-animation="flip" title="Flip Up" data-direction="up"><i class="up long arrow icon"></i></div>
        <div class="ui icon button" data-animation="flip" title="Flip Down" data-direction="down"><i class="down long arrow icon"></i></div>
        <div class="ui icon button" data-animation="flip" title="Flip Right" data-direction="right"><i class="right long arrow icon"></i></div>
      </div>
      <div class="ui ignored icon direction buttons">
        <div class="ui button" title="Flip Over" data-animation="flip" data-direction="over"><i class="retweet icon"></i></div>
        <div class="ui button" title="Flip Back" data-animation="flip" data-direction="back"><i class="flipped retweet icon"></i></div>
      </div>

<div>
<div class="ui circular rotate reveal image">
  <img class="visible content"  src="<?php echo base_url(); ?>/images/v.png" siz="small">
  <img class="hidden content" src="<?php echo base_url(); ?>/images/v1.png">
</div>
</div>
<img class="circular ui small image" src="<?php echo base_url(); ?>/images/v1.png">
<img class="circular ui medium image" src="<?php echo base_url(); ?>/images/v1.png">
<img class="circular ui medium image" src="<?php echo base_url(); ?>/images/v1.png"> !-->
<b>DEVELOPED BY </b>
<div class="two column row">
        <div class="ten wide column">
            <div class="ui fluid accordion">

              <div class=" title ui header">
                <i class="user icon"></i>      
               AADIL HAYAT   
              </div>
              <div class="content">
<table class="ui large basic two column table segment" color="yellow">
         <tr><td><img class="circular ui medium image" src="<?php echo base_url(); ?>/images/a.jpg"></td>
         <td><a href="https://www.facebook.com/hayataadil"><i class="big facebook icon"></i></a>
          <a href="https://plus.google.com/u/0/113338495200331104374/posts"><i class="big google plus icon"></i></a>
          <!-- <i class="big twitter icon"></i> --></td></tr>
       </table></div>

              <div class=" title ui header">
                <i class="user icon"></i>      
              VANDANA GAUTAM 
              </div><div class="content">
              <table class="ui large basic two column table segment" color="yellow">
         <tr><td><img class="circular ui medium image" src="<?php echo base_url(); ?>/images/v.jpg"></td>
         <td><a href="https://www.facebook.com/vandana.gautam.77715"><i class="big facebook icon"></i></a>
          <a href="https://plus.google.com/u/0/100892157497861999258/posts"><i class="big google plus icon"></i></a>
          <!-- <i class="big twitter icon"></i> --></td></tr>
       </table></div>

              <div class="title ui header">
                <i class="user icon"></i>      
               SIDDHARTH GUPTA 
              </div><div class="content">
              <table class="ui large basic two column table segment" color="yellow">
         <tr><td><img class="circular ui medium image" src="<?php echo base_url(); ?>/images/s.jpg"></td>
         <td><a href="https://www.facebook.com/siddharth.gupta.754703"><i class="big  facebook icon"></i></a>
          <i class="big google plus icon"></i>
          <!-- <i class="big twitter icon"></i> --></td></tr>
       </table></div>

              <div class="title ui header">
                <i class="user icon"></i>      
               KRITI JOSHI 
              </div><div class="content">
<table class="ui large basic two column table segment" color="yellow">
         <tr><td><img class="circular ui medium image" src="<?php echo base_url(); ?>/images/k.jpg"></td>
         <td><a href="https://www.facebook.com/kriti.joshi.129"><i class="big facebook icon"></i></a>
          <i class="big google plus icon"></i><!-- <i class="big twitter icon"></i> --></td></tr>
       </table></div><br><br>
<B>UNDER THE MENTORSHIP OF</B><br>
<div class="title ui header">
  <i class="user icon"></i>  
  TRIVENI MAHATHA</div>
  <div class="content">
<table class="ui large basic two column table segment" color="yellow">
         <tr><td><img class="circular ui medium image" src="<?php echo base_url(); ?>/images/t.jpg"></td>
         <td><a href="https://www.facebook.com/triveni.mahatha"><i class="big facebook icon"></i></a>
          <a href="https://plus.google.com/u/0/109462741017055014241/posts"><i class="big google plus icon"></i></a>